package org.graph;

import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicIntegerArray;


public class Graph {
    private final int V;
    private ArrayList<Integer>[] adjList = new ArrayList[0];
    private AtomicIntegerArray visited;

    public Graph(int vertices) {
        this.V = vertices;
        adjList = new ArrayList[vertices];
        visited = new AtomicIntegerArray(V);
        for (int i = 0; i < vertices; ++i) {
            adjList[i] = new ArrayList<>();
        }
    }

    public void addEdge(int src, int dest) {
        if (!adjList[src].contains(dest)) {
            adjList[src].add(dest);
        }
    }

    public int getVisited(int vertex) {
        if (visited == null) {
            throw new IllegalStateException("parallelBFS не запускался");
        }
        return visited.get(vertex);
    }

    public void parallelBFS(int startVertex) throws ExecutionException, InterruptedException {
        visited.set(startVertex, 1);
        int cpuCount = Runtime.getRuntime().availableProcessors();
        ExecutorService executor = Executors.newFixedThreadPool(cpuCount);
        List<Integer> frontier = new ArrayList<>();
        frontier.add(startVertex);
        while (!frontier.isEmpty()) {
            List<Future<List<Integer>>> futures = new ArrayList<>();
            int chunkSize = Math.max(1, frontier.size() / cpuCount);
            for (int i = 0; i < frontier.size(); i += chunkSize) {
                int to = Math.min(i + chunkSize, frontier.size());
                List<Integer> subList = frontier.subList(i, to);
                futures.add(executor.submit(() -> {
                    List<Integer> localNext = new ArrayList<>();
                    for (int v : subList) {
                        localNext.addAll(processVertex(v, visited));
                    }
                    return localNext;
                }));
            }
            List<Integer> nextFrontier = Collections.synchronizedList(new ArrayList<>());
            for (Future<List<Integer>> f : futures) {
                for (int u : f.get()) {
                    if (visited.compareAndSet(u, 0, 1)) {
                        nextFrontier.add(u);
                    }
                }
            }
            frontier = nextFrontier;
        }
        executor.shutdown();
        executor.awaitTermination(1, TimeUnit.MINUTES);
    }

    private List<Integer> processVertex(int vertex, AtomicIntegerArray visited) {
        List<Integer> result = new ArrayList<>();
        for (int u: adjList[vertex]) {
            if (visited.get(u) == 0) {
                result.add(u);
            }
        }
        return result;
    }

    //Generated by ChatGPT
    public void bfs(int startVertex) {
        boolean[] visited = new boolean[V];

        LinkedList<Integer> queue = new LinkedList<>();

        visited[startVertex] = true;
        queue.add(startVertex);

        while (!queue.isEmpty()) {
            startVertex = queue.poll();

            for (int n : adjList[startVertex]) {
                if (!visited[n]) {
                    visited[n] = true;
                    queue.add(n);
                }
            }
        }
    }
}